---
title: "Project 2"
author: "Elena Koung ek8753"
date: "2021-05-08"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>This is a fun dataset and I’m really excited to explore the techniques we learned in class on it. I got this dataset off of Kaggle after looking for esports related data. I am a long time gamer and want to apply my statistical analysis skills to my passion: esports. As someone who has participated and won a variety of tournaments, this dataset contains data that describes the game, its total tournaments, the total payouts, and how many winners for each game. There are 520 total observations. This means there are 520 games.</p>
</div>
<div id="detail-of-variables" class="section level2">
<h2>Detail of Variables</h2>
<pre class="yaml"><code>Variables and their descriptions:

Game: Game name.
ReleaseDate: Release Date of game.
Genre: Genre of game.
TotalEarnings: Total prizepool allocated in tournaments.
OnlineEarnings: Total prizepool allocated in online only tournaments.
TotalPlayers: Total amount of players who received a prize
TotalTournaments: Total amount of tournaments in the site</code></pre>
</div>
<div id="uploading-the-data" class="section level2">
<h2>Uploading the data!</h2>
<pre class="r"><code>esport &lt;- read.csv(&quot;GeneralEsportData.csv&quot;)</code></pre>
<p>I was really glad that the dataset is clean and ready to use :)</p>
</div>
<div id="manova" class="section level2">
<h2>MANOVA!</h2>
<pre class="r"><code>esport %&gt;% group_by(Genre) %&gt;% summarize(n())</code></pre>
<pre><code>## # A tibble: 11 x 2
##    Genre                           `n()`
##  * &lt;fct&gt;                           &lt;int&gt;
##  1 Battle Royale                      13
##  2 Collectible Card Game              17
##  3 Fighting Game                     164
##  4 First-Person Shooter              106
##  5 Multiplayer Online Battle Arena    21
##  6 Puzzle Game                        14
##  7 Racing                             52
##  8 Role-Playing Game                   6
##  9 Sports                             68
## 10 Strategy                           51
## 11 Third-Person Shooter                8</code></pre>
<pre class="r"><code>man &lt;- manova(cbind(TotalEarnings, OnlineEarnings, TotalPlayers, TotalTournaments)~Genre, data=esport)
summary(man)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Genre 10 0.21773 2.9301 40 2036 3.502e-09 ***
## Residuals 509
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man)</code></pre>
<pre><code>## Response TotalEarnings :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Genre 10 7.4891e+15 7.4891e+14 4.7459 1.606e-06 ***
## Residuals 509 8.0320e+16 1.5780e+14
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response OnlineEarnings :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Genre 10 5.3306e+15 5.3306e+14 4.7999 1.305e-06 ***
## Residuals 509 5.6527e+16 1.1106e+14
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response TotalPlayers :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Genre 10 20253506 2025351 3.1691 0.0005905 ***
## Residuals 509 325300059 639096
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response TotalTournaments :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Genre 10 1916591 191659 1.0757 0.3791
## Residuals 509 90687887 178169</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalEarnings, esport$Genre, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: esport$TotalEarnings and esport$Genre
##
## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game 0.03414 - -
## Fighting Game 0.00114 0.52943 -
## First-Person Shooter 0.00911 0.95944 0.16415
## Multiplayer Online Battle Arena 0.19482 0.00016 2.9e-09
## Puzzle Game 0.01368 0.63723 0.97150
## Racing 0.00259 0.57604 0.97986
## Role-Playing Game 0.07903 0.85642 0.85804
## Sports 0.00257 0.61989 0.85830
## Strategy 0.00681 0.82599 0.53826
## Third-Person Shooter 0.04612 0.78732 0.90199
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game - - -
## Fighting Game - - -
## First-Person Shooter - - -
## Multiplayer Online Battle Arena 3.9e-07 - -
## Puzzle Game 0.51882 5.0e-05 -
## Racing 0.31690 1.0e-07 0.96301
## Role-Playing Game 0.81312 0.00433 0.86285
## Sports 0.34168 5.7e-08 0.90319
## Strategy 0.66049 7.1e-07 0.71882
## Third-Person Shooter 0.72505 0.00117 0.90207
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game - - - -
## Fighting Game - - - -
## First-Person Shooter - - - -
## Multiplayer Online Battle Arena - - - -
## Puzzle Game - - - -
## Racing - - - -
## Role-Playing Game 0.87043 - - -
## Sports 0.90609 0.90916 - -
## Strategy 0.63098 0.95501 0.69377 -
## Third-Person Shooter 0.91493 0.95606 0.95981 0.88686
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(esport$OnlineEarnings, esport$Genre, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: esport$OnlineEarnings and esport$Genre
##
## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game 0.22516 - -
## Fighting Game 0.03847 0.55496 -
## First-Person Shooter 0.12592 0.99070 0.23724
## Multiplayer Online Battle Arena 0.00979 3.5e-05 1.6e-10
## Puzzle Game 0.11449 0.65465 0.96846
## Racing 0.05387 0.58719 0.99369
## Role-Playing Game 0.28997 0.87394 0.85662
## Sports 0.05577 0.62420 0.90297
## Strategy 0.10229 0.82732 0.57738
## Third-Person Shooter 0.21471 0.79620 0.91268
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game - - -
## Fighting Game - - -
## First-Person Shooter - - -
## Multiplayer Online Battle Arena 1.9e-08 - -
## Puzzle Game 0.57754 1.2e-05 -
## Racing 0.38011 8.5e-09 0.97416
## Role-Playing Game 0.86322 0.00200 0.85992
## Sports 0.40359 4.0e-09 0.92239
## Strategy 0.73340 6.3e-08 0.73943
## Third-Person Shooter 0.76898 0.00043 0.90890
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game - - - -
## Fighting Game - - - -
## First-Person Shooter - - - -
## Multiplayer Online Battle Arena - - - -
## Puzzle Game - - - -
## Racing - - - -
## Role-Playing Game 0.85943 - - -
## Sports 0.91853 0.89257 - -
## Strategy 0.64572 0.97366 0.69846 -
## Third-Person Shooter 0.91410 0.94774 0.95280 0.89613
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalPlayers, esport$Genre, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: esport$TotalPlayers and esport$Genre
##
## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game 0.04616 - -
## Fighting Game 0.00114 0.41813 -
## First-Person Shooter 0.04618 0.56844 0.00450
## Multiplayer Online Battle Arena 0.80272 0.04747 0.00025
## Puzzle Game 0.00785 0.41952 0.75999
## Racing 0.00182 0.40000 0.85616
## Role-Playing Game 0.07350 0.75429 0.88953
## Sports 0.00143 0.38871 0.84906
## Strategy 0.00881 0.77383 0.43249
## Third-Person Shooter 0.03164 0.58884 0.94405
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game - - -
## Fighting Game - - -
## First-Person Shooter - - -
## Multiplayer Online Battle Arena 0.03715 - -
## Puzzle Game 0.12183 0.00668 -
## Racing 0.02358 0.00068 0.85189
## Role-Playing Game 0.47822 0.08576 0.76980
## Sports 0.01402 0.00045 0.84437
## Strategy 0.17843 0.00513 0.48456
## Third-Person Shooter 0.29924 0.03463 0.89293
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game - - - -
## Fighting Game - - - -
## First-Person Shooter - - - -
## Multiplayer Online Battle Arena - - - -
## Puzzle Game - - - -
## Racing - - - -
## Role-Playing Game 0.84085 - - -
## Sports 0.99395 0.84147 - -
## Strategy 0.43251 0.87453 0.40796 -
## Third-Person Shooter 0.99278 0.87765 0.99564 0.69076
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalTournaments,  esport$Genre, p.adj=&quot;none&quot;)</code></pre>
<pre><code>##
## Pairwise comparisons using t tests with pooled SD
##
## data: esport$TotalTournaments and esport$Genre
##
## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game 0.918 - -
## Fighting Game 0.674 0.743 -
## First-Person Shooter 0.975 0.858 0.296
## Multiplayer Online Battle Arena 0.339 0.250 0.048
## Puzzle Game 0.525 0.566 0.657
## Racing 0.504 0.544 0.588
## Role-Playing Game 0.725 0.774 0.899
## Sports 0.579 0.631 0.747
## Strategy 0.512 0.389 0.043
## Third-Person Shooter 0.614 0.660 0.772
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game - - -
## Fighting Game - - -
## First-Person Shooter - - -
## Multiplayer Online Battle Arena 0.169 - -
## Puzzle Game 0.372 0.092 -
## Racing 0.201 0.035 0.901
## Role-Playing Game 0.663 0.269 0.884
## Sports 0.255 0.043 0.793
## Strategy 0.254 0.605 0.137
## Third-Person Shooter 0.521 0.175 0.967
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game - - - -
## Fighting Game - - - -
## First-Person Shooter - - - -
## Multiplayer Online Battle Arena - - - -
## Puzzle Game - - - -
## Racing - - - -
## Role-Playing Game 0.938 - - -
## Sports 0.830 0.989 - -
## Strategy 0.037 0.382 0.045 -
## Third-Person Shooter 0.960 0.922 0.876 0.258
##
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalEarnings, esport$Genre, p.adj=&quot;none&quot;)$p.value&lt;0.05/225</code></pre>
<pre><code>## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game FALSE NA NA
## Fighting Game FALSE FALSE NA
## First-Person Shooter FALSE FALSE FALSE
## Multiplayer Online Battle Arena FALSE TRUE TRUE
## Puzzle Game FALSE FALSE FALSE
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game NA NA NA
## Fighting Game NA NA NA
## First-Person Shooter NA NA NA
## Multiplayer Online Battle Arena TRUE NA NA
## Puzzle Game FALSE TRUE NA
## Racing FALSE TRUE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE TRUE FALSE
## Strategy FALSE TRUE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game NA NA NA NA
## Fighting Game NA NA NA NA
## First-Person Shooter NA NA NA NA
## Multiplayer Online Battle Arena NA NA NA NA
## Puzzle Game NA NA NA NA
## Racing NA NA NA NA
## Role-Playing Game FALSE NA NA NA
## Sports FALSE FALSE NA NA
## Strategy FALSE FALSE FALSE NA
## Third-Person Shooter FALSE FALSE FALSE FALSE</code></pre>
<pre class="r"><code>pairwise.t.test(esport$OnlineEarnings, esport$Genre, p.adj=&quot;none&quot;)$p.value&lt;0.05/225</code></pre>
<pre><code>## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game FALSE NA NA
## Fighting Game FALSE FALSE NA
## First-Person Shooter FALSE FALSE FALSE
## Multiplayer Online Battle Arena FALSE TRUE TRUE
## Puzzle Game FALSE FALSE FALSE
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game NA NA NA
## Fighting Game NA NA NA
## First-Person Shooter NA NA NA
## Multiplayer Online Battle Arena TRUE NA NA
## Puzzle Game FALSE TRUE NA
## Racing FALSE TRUE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE TRUE FALSE
## Strategy FALSE TRUE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game NA NA NA NA
## Fighting Game NA NA NA NA
## First-Person Shooter NA NA NA NA
## Multiplayer Online Battle Arena NA NA NA NA
## Puzzle Game NA NA NA NA
## Racing NA NA NA NA
## Role-Playing Game FALSE NA NA NA
## Sports FALSE FALSE NA NA
## Strategy FALSE FALSE FALSE NA
## Third-Person Shooter FALSE FALSE FALSE FALSE</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalPlayers, esport$Genre, p.adj=&quot;none&quot;)$p.value&lt;0.05/225</code></pre>
<pre><code>## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game FALSE NA NA
## Fighting Game FALSE FALSE NA
## First-Person Shooter FALSE FALSE FALSE
## Multiplayer Online Battle Arena FALSE FALSE FALSE
## Puzzle Game FALSE FALSE FALSE
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game NA NA NA
## Fighting Game NA NA NA
## First-Person Shooter NA NA NA
## Multiplayer Online Battle Arena FALSE NA NA
## Puzzle Game FALSE FALSE NA
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game NA NA NA NA
## Fighting Game NA NA NA NA
## First-Person Shooter NA NA NA NA
## Multiplayer Online Battle Arena NA NA NA NA
## Puzzle Game NA NA NA NA
## Racing NA NA NA NA
## Role-Playing Game FALSE NA NA NA
## Sports FALSE FALSE NA NA
## Strategy FALSE FALSE FALSE NA
## Third-Person Shooter FALSE FALSE FALSE FALSE</code></pre>
<pre class="r"><code>pairwise.t.test(esport$TotalTournaments,  esport$Genre, p.adj=&quot;none&quot;)$p.value&lt;0.05/225</code></pre>
<pre><code>## Battle Royale Collectible Card Game Fighting Game
## Collectible Card Game FALSE NA NA
## Fighting Game FALSE FALSE NA
## First-Person Shooter FALSE FALSE FALSE
## Multiplayer Online Battle Arena FALSE FALSE FALSE
## Puzzle Game FALSE FALSE FALSE
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## First-Person Shooter Multiplayer Online Battle Arena
Puzzle Game
## Collectible Card Game NA NA NA
## Fighting Game NA NA NA
## First-Person Shooter NA NA NA
## Multiplayer Online Battle Arena FALSE NA NA
## Puzzle Game FALSE FALSE NA
## Racing FALSE FALSE FALSE
## Role-Playing Game FALSE FALSE FALSE
## Sports FALSE FALSE FALSE
## Strategy FALSE FALSE FALSE
## Third-Person Shooter FALSE FALSE FALSE
## Racing Role-Playing Game Sports Strategy
## Collectible Card Game NA NA NA NA
## Fighting Game NA NA NA NA
## First-Person Shooter NA NA NA NA
## Multiplayer Online Battle Arena NA NA NA NA
## Puzzle Game NA NA NA NA
## Racing NA NA NA NA
## Role-Playing Game FALSE NA NA NA
## Sports FALSE FALSE NA NA
## Strategy FALSE FALSE FALSE NA
## Third-Person Shooter FALSE FALSE FALSE FALSE</code></pre>
<pre class="yaml"><code>Checking MANOVA assumptions:
1. Random samples, independent observations, yes we can assume this.
2. Multivariate normality of DVs, no, some groups have less than 25 observations, namely for Battle Royale, Collectible Card Game, Multiplayer Online Battle Arena, Puzzle Game, Role-Playing Game, Third-Person Shooter.
3. Homogeneity of within-group covariance matrices, yes we can assume this.
4. Linear relationships among DVs, it&#39;s possible to assume this. I would assume that a more popular game (more players and more tournaments) would have greater earnings (total and online)
5. No extreme univariate or multivariate outliers, yes we can assume this. 
6. No multicollinearity (i.e., DVs should not be too correlated), yes we can assume this</code></pre>
<p>Assume MANOVA to be an appropriate analysis technique. A one-way MANOVA was conducted to determine the effect of the <code>Genre</code>
on tournament elements: <code>TotalEarnings</code>, <code>OnlineEarnings</code>, <code>TotalPlayers</code>, <code>TotalTournaments</code>. All the elements differ by <code>Genre</code> except <code>TotalTournaments</code> since every P-value is less than 0.001.
Significant differences were found among the <code>Genre</code>s for at least one of the dependent variables. Pillai trace = 0.21773, pseudo F(40,2036), p = 3.502e-09 &lt; 0.001. Univariate ANOVAs for each dependent variable were conducted as follow-up tests to the MANOVA, using the Bonferroni method for controlling Type I error rates for multiple comparisons. The univariate ANOVAs for each element were also significant at 0.001 significance level.
1 MANOVA + 4 ANOVAs + 4 pairwise t tests (4*(10+9+8+7+6+5+4+3+2+1)) = 225 tests, so use 0.05 / 225 = 0.0002 significance.</p>
<p>Post hoc analysis was performed conducting pairwise comparisons to determine which <code>Genre</code>s differed in elements. When using Bonferroni = 0.05 / 225 = 0.0002. The probability that at least 1 type 1 error occurred is 1-.95^225 or 0.9999, as we have 225 hypothesis tests.</p>
<p>After correction:</p>
<p>For <code>TotalEarnings</code>: The results that are significant are Multiplayer Online Battle Arena and Collectible Card Game, Multiplayer Online Battle Arena and Fighting Game, Multiplayer Online Battle Arena and First-Person Shooter, Multiplayer Online Battle Arena and Puzzle Game, Multiplayer Online Battle Arena and Racing, Multiplayer Online Battle Arena and Sports, Multiplayer Online Battle Arena and Strategy.</p>
<p>For <code>OnlineEarnings</code>: The results that are significant are Multiplayer Online Battle Arena and Collectible Card Game, Multiplayer Online Battle Arena and First Person Shooter, Multiplayer Online Battle Arena and Fighting Game, Multiplayer Online Battle Arena and Puzzle Game, Multiplayer Online Battle Arena and Racing, Multiplayer Online Battle Arena and Sports, Multiplayer Online Battle Arena and Strategy.</p>
<p>For <code>TotalPlayers</code>: There are no significant results.</p>
<p>For <code>TotalTournaments</code>: There are no significant results.</p>
</div>
<div id="randomization-test" class="section level2">
<h2>Randomization Test!</h2>
<p>I want to know if there is an association with the <code>Genre</code> of game and <code>TotalEarnings</code> for the prize pool, specifically for the <code>Genre</code>s: Battle Royale and Multiplayer Online Battle Arena since they are the two highest prized genres.
So I want to test whether there was a difference in mean <code>TotalEarnings</code> between the two Genres.</p>
<p><em>Null hypothesis</em> : There is no difference in the mean TotalEarnings between Battle Royale and Multiplayer Online Battle Arena.</p>
<p><em>Alternative hypothesis</em> : There is a significant difference in the mean TotalEarnings between Battle Royale and Multiplayer Online Battle Arena.</p>
<pre class="r"><code>esport %&gt;% group_by(Genre) %&gt;% summarize(n=mean(TotalEarnings))</code></pre>
<pre><code>## # A tibble: 11 x 2
##    Genre                                   n
##  * &lt;fct&gt;                               &lt;dbl&gt;
##  1 Battle Royale                   11973998.
##  2 Collectible Card Game            2142825.
##  3 Fighting Game                     128612.
##  4 First-Person Shooter             2309818.
##  5 Multiplayer Online Battle Arena 17728953.
##  6 Puzzle Game                         3595.
##  7 Racing                            179112.
##  8 Role-Playing Game                1062992.
##  9 Sports                            452252.
## 10 Strategy                         1368985.
## 11 Third-Person Shooter              688998.</code></pre>
<pre class="r"><code>br &lt;- esport %&gt;% filter(Genre==&quot;Battle Royale&quot;) %&gt;% select(Genre,TotalEarnings)
moba &lt;- esport %&gt;% filter(Genre==&quot;Multiplayer Online Battle Arena&quot;) %&gt;% select(Genre,TotalEarnings)

comp &lt;- rbind(br,moba)
ggplot(comp,aes(TotalEarnings,fill=Genre))+geom_histogram(bins=6.5)+
facet_wrap(~Genre,ncol=2)+theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>rand_dist&lt;-vector()
for(i in 1:5000){
  new&lt;-data.frame(te=sample(comp$TotalEarnings),genre=comp$Genre)
  rand_dist[i]&lt;-mean(new[new$genre==&quot;Battle Royale&quot;,]$te)-
  mean(new[new$genre==&quot;Multiplayer Online Battle Arena&quot;,]$te)}
diffmeans &lt;- esport %&gt;% group_by(Genre) %&gt;% filter(Genre==&quot;Battle Royale&quot; | Genre==&quot;Multiplayer Online Battle Arena&quot;) %&gt;% summarize(means=mean(TotalEarnings)) 
11973998- 17728953</code></pre>
<pre><code>## [1] -5754955</code></pre>
<pre class="r"><code>diffmeans</code></pre>
<pre><code>## # A tibble: 2 x 2
##   Genre                               means
##   &lt;fct&gt;                               &lt;dbl&gt;
## 1 Battle Royale                   11973998.
## 2 Multiplayer Online Battle Arena 17728953.</code></pre>
<pre class="r"><code>{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-5754955, 5754955),col=&quot;red&quot;)}</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;5754955 | rand_dist &lt; -5754955)</code></pre>
<pre><code>## [1] 0.8418</code></pre>
<pre class="r"><code>t.test(data=comp,TotalEarnings~Genre)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: TotalEarnings by Genre
## t = -0.41304, df = 31.658, p-value = 0.6824
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -34147896 22637987
## sample estimates:
## mean in group Battle Royale mean in group Multiplayer
Online Battle Arena
## 11973998 17728953</code></pre>
<p>The randomization test has less power so the p-value is higher. The high p-value suggests that there is no significant difference in means. There is high variance in the difference in means.</p>
</div>
<div id="linear-regression-modelling" class="section level2">
<h2>Linear Regression Modelling!</h2>
<pre class="r"><code>esport$TotalEarnings_c = esport$TotalEarnings-mean(esport$TotalEarnings, na.rm=T)
esport$OnlineEarnings_c = esport$OnlineEarnings-mean(esport$OnlineEarnings, na.rm=T)

fit &lt;- lm(TotalPlayers~TotalEarnings_c*OnlineEarnings_c,data=esport)</code></pre>
</div>
<div id="interpreting-coefficients" class="section level2">
<h2>Interpreting Coefficients!</h2>
<pre class="r"><code>summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = TotalPlayers ~ TotalEarnings_c *
OnlineEarnings_c,
## data = esport)
##
## Residuals:
## Min 1Q Median 3Q Max
## -2836.7 -41.3 -35.3 -1.4 5103.0
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.676e+02 1.688e+01 15.853 &lt; 2e-16 ***
## TotalEarnings_c 6.066e-05 6.762e-06 8.971 &lt; 2e-16 ***
## OnlineEarnings_c 8.034e-05 1.097e-05 7.324 9.35e-13 ***
## TotalEarnings_c:OnlineEarnings_c -5.479e-13 2.483e-14
-22.067 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 376.8 on 516 degrees of freedom
## Multiple R-squared: 0.788, Adjusted R-squared: 0.7867
## F-statistic: 639.2 on 3 and 516 DF, p-value: &lt; 2.2e-16</code></pre>
<p>The intercept is 267.6, which suggests that a tournament with mean <code>TotalEarnings</code> and mean <code>OnlineEarnings</code> will have about 267-268 players. The coefficient for <code>TotalEarnings_c</code> means that for every $1 increase in mean prize money, there will be an increase of 6.066e-05 of a player. The coefficient for <code>OnlineEarnings_c</code> means that for every $1 increase in mean prize money, there will be 8.034e-05 of a player. The interaction of <code>TotalEarnings_c</code> and <code>OnlineEarnings_c</code> suggests that there is a decrease of -5.479e-13 of a player for every $1 increase in both <code>TotalEarnings_c</code> and <code>OnlineEarnings_c</code>.</p>
<p>Below mean <code>OnlineEarnings_c</code> leads to an increase in the slope of total earnings and players.
Above mean <code>OnlineEarnings_c</code>leads to a decrease in the slope of <code>TotalEarnings_c</code> and <code>TotalPlayers</code>.
It is interesting to see that below mean <code>OnlineEarnings_c</code> has the steepest slope, followed by the mean <code>OnlineEarnings_c</code>and then above the mean `OnlineEarnings_c. </p>
</div>
<div id="plotting-linear-regression" class="section level2">
<h2>Plotting Linear Regression!</h2>
<pre class="r"><code>library(interactions)
interact_plot(fit,pred =  TotalEarnings_c, modx = OnlineEarnings_c)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The coefficient of determination, R-squared, is the proportion of the variation that explained by the regression. Multiple R-squared: 0.788, Adjusted R-squared: 0.7867. Thus, this linear model accounts for about 78% of the variation in the data.</p>
</div>
<div id="checking-assumptions" class="section level2">
<h2>Checking Assumptions!</h2>
<p>Check assumptions of linearity, normality, and homoscedasticity graphically.</p>
</div>
<div id="linearity" class="section level2">
<h2>Linearity?</h2>
<pre class="r"><code>esport %&gt;% ggplot(aes(TotalEarnings_c,TotalPlayers)) + geom_point()</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>esport %&gt;% ggplot(aes(OnlineEarnings_c,TotalPlayers)) + geom_point()</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-7-2.png" width="576" style="display: block; margin: auto;" />
It is a little hard to tell because of the outliers. But it looks like both predictors, <code>TotalEarnings</code> and <code>OnlineEarnings</code> should probably fail the linearity assumption. There is a hint of slight linearity but is hard to tell with the outliers.</p>
</div>
<div id="normality" class="section level2">
<h2>Normality?</h2>
<pre class="r"><code>resids1 &lt;- lm(TotalPlayers~OnlineEarnings, data=esport)$residuals
ggplot()+geom_histogram(aes(resids1),bins=50)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-8-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fitted1&lt;-lm(TotalPlayers~OnlineEarnings, data=esport)$fitted.values
ggplot()+geom_point(aes(fitted1,resids1))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-8-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids2&lt;- lm(TotalPlayers~TotalEarnings, data=esport)$residuals
ggplot()+geom_histogram(aes(resids2),bins=50)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-8-3.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fitted2&lt;-lm(TotalPlayers~TotalEarnings, data=esport)$fitted.values
ggplot()+geom_point(aes(fitted2,resids2))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-8-4.png" width="576" style="display: block; margin: auto;" />
The histograms are really skewed for both predictors so they do not look normal. It looks like there is large variance in residuals for both predictors as well.</p>
</div>
<div id="homoscedasticity" class="section level2">
<h2>Homoscedasticity?</h2>
<pre class="r"><code>library(sandwich)
library(lmtest)
fit&lt;-lm(TotalPlayers~TotalEarnings_c*OnlineEarnings_c,data=esport)
bptest(fit) #H0: homoskedastic</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 274.77, df = 3, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>## Estimate Std. Error
## (Intercept) 2.675866e+02 8.187437e+01
## TotalEarnings_c 6.065886e-05 2.007101e-04
## OnlineEarnings_c 8.033622e-05 2.473643e-04
## TotalEarnings_c:OnlineEarnings_c -5.479117e-13
1.118232e-12</code></pre>
<p>The calculated p value for Breusch-Pagan (bp) test is &lt; 2.2e-16, which we can reject the null that the data is homoscedastic. Thus, the data is not homoscedastic but heteroscedastic.</p>
<p>The data fails all assumptions…</p>
</div>
<div id="recomputing-regression" class="section level2">
<h2>Recomputing Regression!</h2>
<p>Need Heteroscedasticity Robust Standard Errors and Bootstrapped SEs.</p>
<pre class="r"><code>coeftest(fit)</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.6759e+02 1.6879e+01 15.8531 &lt; 2.2e-16 ***
## TotalEarnings_c 6.0659e-05 6.7615e-06 8.9712 &lt; 2.2e-16
***
## OnlineEarnings_c 8.0336e-05 1.0970e-05 7.3235 9.348e-13
***
## TotalEarnings_c:OnlineEarnings_c -5.4791e-13 2.4829e-14
-22.0674 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit, vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.6759e+02 8.1874e+01 3.2683 0.001154 **
## TotalEarnings_c 6.0659e-05 2.0071e-04 0.3022 0.762605
## OnlineEarnings_c 8.0336e-05 2.4736e-04 0.3248 0.745488
## TotalEarnings_c:OnlineEarnings_c -5.4791e-13 1.1182e-12
-0.4900 0.624356
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The original model said that all coefficents were significant in the regression. After using Robust SE, we see that only the intercept remains significant at the 0.01 level. The SE increased from the original to the Robust SE.</p>
</div>
<div id="bootstrap-se" class="section level2">
<h2>Bootstrap SE!</h2>
<pre class="r"><code>set.seed(1234)
boot_dat&lt;- sample_frac(esport, replace=T)

samp_distn&lt;-replicate(5000, {
boot_dat &lt;- sample_frac(esport, replace=T)
fit &lt;- lm(TotalPlayers~TotalEarnings_c*OnlineEarnings_c, data=boot_dat) 
coef(fit) 
})
samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>## (Intercept) TotalEarnings_c OnlineEarnings_c
TotalEarnings_c:OnlineEarnings_c
## 1 42.47318 0.0001013776 0.0001257641 7.651835e-13</code></pre>
<pre class="r"><code>samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% pivot_longer(1:4) %&gt;% group_by(name) %&gt;%
summarize(lower=quantile(value,.025), upper=quantile(value,.975))</code></pre>
<pre><code>## # A tibble: 4 x 3
##   name                                 lower    upper
## * &lt;chr&gt;                                &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)                       1.61e+ 2 3.35e+ 2
## 2 OnlineEarnings_c                 -2.53e- 4 1.82e- 4
## 3 TotalEarnings_c                  -4.45e- 5 3.07e- 4
## 4 TotalEarnings_c:OnlineEarnings_c -2.78e-12 9.74e-13</code></pre>
<p>I chose to resample observations. The SE through Bootstrap are smaller than the SE through Robust SE. By observing that our bootstrap SEs for TotalEarnings_c, OnlineEarnings_c, are inside the range of 95% CI, these estimates are insignificant. However, the estimate for the intercept and TotalEarnings_c:OnlineEarnings_c is outside of this range, making it significant.</p>
</div>
<div id="logistic-regression-modelling" class="section level2">
<h2>Logistic Regression Modelling!</h2>
<p>I want to see how well a logistic model can predict a “highly prized game”. I define this by a game whose TotalEarnings are greater than 10,000 USD.</p>
<pre class="r"><code>esportb &lt;- esport %&gt;% mutate(y = ifelse(TotalEarnings&gt;10000,1,0))
esportb &lt;- esportb %&gt;% filter(Genre != &quot;Role-Playing Game&quot;) 
esportb %&gt;% group_by(Genre) %&gt;% summarize(n())</code></pre>
<pre><code>## # A tibble: 10 x 2
##    Genre                           `n()`
##  * &lt;fct&gt;                           &lt;int&gt;
##  1 Battle Royale                      13
##  2 Collectible Card Game              17
##  3 Fighting Game                     164
##  4 First-Person Shooter              106
##  5 Multiplayer Online Battle Arena    21
##  6 Puzzle Game                        14
##  7 Racing                             52
##  8 Sports                             68
##  9 Strategy                           51
## 10 Third-Person Shooter                8</code></pre>
<pre class="r"><code>lrm &lt;- glm(y~ Genre + TotalTournaments, data=esportb, family=&quot;binomial&quot;)
coeftest(lrm)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 0.601096 0.835499 0.7194 0.4718664
## GenreCollectible Card Game -2.123686 1.101444 -1.9281
0.0538436 .
## GenreFighting Game -2.946988 0.875597 -3.3657 0.0007635
***
## GenreFirst-Person Shooter -0.739829 0.878901 -0.8418
0.3999192
## GenreMultiplayer Online Battle Arena -0.764863 1.038496
-0.7365 0.4614201
## GenrePuzzle Game -3.502153 1.182569 -2.9615 0.0030617 **
## GenreRacing -0.633730 0.897609 -0.7060 0.4801756
## GenreSports -0.225241 0.887056 -0.2539 0.7995578
## GenreStrategy -1.060934 0.907835 -1.1686 0.2425478
## GenreThird-Person Shooter 0.234720 1.392707 0.1685
0.8661621
## TotalTournaments 0.185386 0.025262 7.3386 2.159e-13 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(lrm))</code></pre>
<pre><code>## (Intercept) GenreCollectible Card Game
## 1.82411738 0.11959001
## GenreFighting Game GenreFirst-Person Shooter
## 0.05249758 0.47719567
## GenreMultiplayer Online Battle Arena GenrePuzzle Game
## 0.46539754 0.03013245
## GenreRacing GenreSports
## 0.53060890 0.79832405
## GenreStrategy GenreThird-Person Shooter
## 0.34613226 1.26455515
## TotalTournaments
## 1.20368262</code></pre>
<p>logodds = 0.601096 + Collectible Card Game(-2.123686) + Fighting Game(-2.946988) + First-Person Shooter(-0.739829) + Multiplayer Online Battle Arena(-0.764863) + Puzzle Game(-3.502153) + Racing(-0.633730) + Sports(-0.225241) + Strategy(-1.060934) + Third-Person Shooter(0.234720) + TotalTournaments(0.185386)</p>
<p>Battle Royale is the <code>Genre</code> used as reference.
The odds of Battle Royale to Collectible Card Game is 0.11959001. The odds of Battle Royale to Fighting Game is 0.05249758. As we continue this interpretation for the rest of the different <code>Genre</code>s, it is obvious that all Genres but 1, Third-Person Shooter, have less odds of being a highly prized game than the reference <code>Genre</code>: Battle Royale.</p>
<p>An increase in 1 <code>TotalTournaments</code> affects the logodds by an increase of 0.185386. So the odds of a tournament being highly prized is increased by 1.20368262.</p>
<p>Note: ended up removing Role-Playing Game from Genre to improve model.</p>
</div>
<div id="confusion-matrix" class="section level2">
<h2>Confusion Matrix!</h2>
<pre class="r"><code>prob &lt;- predict(lrm,type=&quot;response&quot;)
table(predict=as.numeric(prob&gt;.5),truth=esportb$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   132  26 158
##     1    59 297 356
##     Sum 191 323 514</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}
class_diag(prob,esportb$y)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.8346304 0.9195046 0.6910995 0.8342697 0.8969089</code></pre>
<p>The Accuracy is 0.8346304.
The Sensitivity (TPR) is 0.9195046.
The Specificity (TNR) is 0.6910995.
The Precision (PPV) is 0.8342697.
The AUC is 0.8969089. This means that this is a good model for predicting if the game is having <code>TotalEarnings</code> &gt; 10000.</p>
<pre class="r"><code>esportb$logit &lt;- predict(lrm)
esportb$outcome &lt;- factor(esportb$y,levels=c(&quot;0&quot;,&quot;1&quot;))
ggplot(esportb,aes(logit, fill=outcome))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2) + xlim(-1, 100)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-15-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(esportb,aes(logit, fill=outcome))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2) + xlim(-1, 10)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-15-2.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(esportb)+geom_roc(aes(d=y,m=prob), n.cuts=0)
ROCplot</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-16-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8969089</code></pre>
<p>This AUC matches the AUC I got from using the class_diag() function. With this AUC value, I can say that this is a good model for predicting if the game is having <code>TotalEarnings</code> &gt; 10000 based on the predictors of <code>Genre</code> and <code>TotalTournaments</code>.</p>
</div>
<div id="using-many-predictors-on-logistic-regression" class="section level2">
<h2>Using many predictors on Logistic Regression!</h2>
<p>Now I predict if a game’s tournament will have <code>TotalEarnings</code> &gt; 10000 based on the predictors: <code>Genre</code> + <code>TotalTournaments</code> + <code>OnlineEarnings</code> + <code>TotalPlayers</code> + <code>ReleaseDate</code>.</p>
<pre class="r"><code>lrm2 &lt;- glm(y~ Genre + TotalTournaments + OnlineEarnings + TotalPlayers + ReleaseDate, data=esportb, family=&quot;binomial&quot;)
coeftest(lrm2)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -2.5335e+02 8.8979e+01 -2.8473 0.0044086 **
## GenreCollectible Card Game -2.2343e+00 1.2659e+00
-1.7650 0.0775696 .
## GenreFighting Game -3.8127e+00 1.0701e+00 -3.5631
0.0003666 ***
## GenreFirst-Person Shooter -2.9173e+00 1.1149e+00 -2.6166
0.0088814 **
## GenreMultiplayer Online Battle Arena -1.0513e+00
1.2931e+00 -0.8129 0.4162470
## GenrePuzzle Game -3.3519e+00 1.4341e+00 -2.3373
0.0194251 *
## GenreRacing -2.0999e+00 1.1216e+00 -1.8722 0.0611793 .
## GenreSports -2.1021e+00 1.1777e+00 -1.7850 0.0742667 .
## GenreStrategy -1.6612e+00 1.0906e+00 -1.5232 0.1277048
## GenreThird-Person Shooter -1.5326e+00 1.5868e+00 -0.9658
0.3341221
## TotalTournaments -3.3037e-02 1.9073e-02 -1.7321
0.0832479 .
## OnlineEarnings 4.0542e-04 6.9283e-05 5.8517 4.865e-09
***
## TotalPlayers 5.4200e-02 1.1448e-02 4.7342 2.199e-06 ***
## ReleaseDate 1.2559e-01 4.4091e-02 2.8484 0.0043939 **
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(lrm2))</code></pre>
<pre><code>## (Intercept) GenreCollectible Card Game
## 9.337656e-111 1.070669e-01
## GenreFighting Game GenreFirst-Person Shooter
## 2.208878e-02 5.408055e-02
## GenreMultiplayer Online Battle Arena GenrePuzzle Game
## 3.494975e-01 3.501839e-02
## GenreRacing GenreSports
## 1.224739e-01 1.221980e-01
## GenreStrategy GenreThird-Person Shooter
## 1.899054e-01 2.159674e-01
## TotalTournaments OnlineEarnings
## 9.675030e-01 1.000406e+00
## TotalPlayers ReleaseDate
## 1.055695e+00 1.133815e+00</code></pre>
<pre class="r"><code>prob2 &lt;- predict(lrm2,type=&quot;response&quot;)
table(predict=as.numeric(prob2&gt;.5),truth=esportb$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0   178  22 200
##     1    13 301 314
##     Sum 191 323 514</code></pre>
<pre class="r"><code>class_diag(prob2,esportb$y)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9319066 0.9318885 0.9319372 0.9585987 0.9848929</code></pre>
<p>The Accuracy is 0.9319066.
The Sensitivity (TPR) is 0.9318885.
The Specificity (TNR) is 0.9319372.
The Precision (PPV) is 0.9585987.
The AUC is 0.9848929. This means that this is a great model for predicting if the game is having <code>TotalEarnings</code> &gt; 10000.</p>
</div>
<div id="fold-cv" class="section level2">
<h2>10-fold CV!</h2>
<pre class="r"><code>set.seed(1234)
k = 10


data &lt;- esportb[sample(nrow(esportb)),] 
folds &lt;- cut(seq(1:nrow(esportb)),breaks=k,labels=F) 

diags &lt;- NULL
for(i in 1:k){         
train &lt;- data[folds!=i,] 
test &lt;- data[folds==i,]  

truth &lt;- test$y

fit &lt;- glm(y ~ Genre + TotalTournaments + OnlineEarnings + TotalPlayers + ReleaseDate, data=train, family=&quot;binomial&quot;)
probs &lt;- predict(fit, newdata = test, type=&quot;resp&quot;)

diags &lt;- rbind(diags,class_diag(probs,test$y)) 
}

summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9183635 0.9225357 0.9147702 0.9451259 0.9814307</code></pre>
<p>The AUC from the original model was 0.9848929. After 10-fold CV, the AUC is 0.9814307, which is a slight decrease. Since the model is still great and the difference is quite small, I conclude that this model does not show signs of overfitting.</p>
<p>The average out-of-sample classification diagnostics are:
The Accuracy is 0.9183635.
The Sensitivity (TPR) is 0.9225357.
The Specificity (TNR) is 0.9147702.
The Precision (PPV) is 0.9451259.</p>
</div>
<div id="lasso" class="section level2">
<h2>LASSO!</h2>
<pre class="r"><code>library(glmnet)
set.seed(1234)

z &lt;- as.matrix(esportb$y) 
x &lt;- model.matrix(z ~ Genre + TotalTournaments + OnlineEarnings + TotalPlayers + ReleaseDate, data=esportb)[,-1]
head(x)</code></pre>
<pre><code>## GenreCollectible Card Game GenreFighting Game
GenreFirst-Person Shooter
## 1 0 0 0
## 2 0 0 0
## 3 0 0 0
## 4 0 0 0
## 5 0 0 0
## 6 0 0 0
## GenreMultiplayer Online Battle Arena GenrePuzzle Game
GenreRacing GenreRole-Playing Game
## 1 0 0 0 0
## 2 0 0 0 0
## 3 0 0 0 0
## 4 0 0 0 0
## 5 0 0 0 0
## 6 0 0 0 0
## GenreSports GenreStrategy GenreThird-Person Shooter
TotalTournaments OnlineEarnings TotalPlayers
## 1 0 1 0 96 156839.9 255
## 2 0 1 0 815 619037.9 1172
## 3 0 1 0 76 41500.0 106
## 4 0 1 0 10 0.0 17
## 5 0 1 0 6 52000.0 22
## 6 0 1 0 7 0.0 12
## ReleaseDate
## 1 1997
## 2 1999
## 3 2005
## 4 2011
## 5 2002
## 6 2018</code></pre>
<pre class="r"><code>cv &lt;- cv.glmnet(x, z, family=&quot;binomial&quot;)
cv</code></pre>
<pre><code>## 
## Call:  cv.glmnet(x = x, y = z, family = &quot;binomial&quot;) 
## 
## Measure: Binomial Deviance 
## 
##        Lambda Measure      SE Nonzero
## min 5.907e-05  0.5192 0.08044      12
## 1se 1.365e-04  0.5994 0.07568      13</code></pre>
<pre class="r"><code>{plot(cv$glmnet.fit, &quot;lambda&quot;, label=TRUE); abline(v = log(cv$lambda.1se)); abline(v = log(cv$lambda.min),lty=2)}</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-19-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>lasso &lt;- glmnet(x, z, family=&quot;binomial&quot;, lambda=cv$lambda.min)
lasso</code></pre>
<pre><code>##
## Call: glmnet(x = x, y = z, family = &quot;binomial&quot;, lambda =
cv$lambda.min)
##
## Df %Dev Lambda
## 1 12 68.6 5.907e-05</code></pre>
<pre class="r"><code>coef(lasso)</code></pre>
<pre><code>## 15 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                                 s0
## (Intercept)                          -2.429475e+01
## GenreCollectible Card Game           -1.911546e+00
## GenreFighting Game                   -2.636135e+00
## GenreFirst-Person Shooter            -1.701535e+00
## GenreMultiplayer Online Battle Arena -1.234164e+00
## GenrePuzzle Game                     -2.618775e+00
## GenreRacing                          -1.188355e+00
## GenreRole-Playing Game                .           
## GenreSports                          -1.204635e+00
## GenreStrategy                        -1.630908e+00
## GenreThird-Person Shooter            -9.095024e-01
## TotalTournaments                      .           
## OnlineEarnings                        7.904838e-05
## TotalPlayers                          4.383062e-02
## ReleaseDate                           1.207549e-02</code></pre>
<pre class="r"><code>lasso_dat &lt;- esportb %&gt;% mutate(CollectibleCardGame = ifelse(Genre==&quot;Collectible Card Game&quot;, 1, 0) ) %&gt;% mutate(FightingGame = ifelse(Genre==&quot;Fighting Game&quot;, 1, 0) ) %&gt;% mutate(FPS = ifelse(Genre==&quot;First-Person Shooter&quot;, 1, 0) )%&gt;% mutate(MOBA = ifelse(Genre==&quot;Multiplayer Online Battle Arena&quot;, 1, 0) ) %&gt;% mutate(PuzzleGame = ifelse(Genre==&quot;Puzzle Game&quot;, 1, 0) ) %&gt;% mutate(Racing = ifelse(Genre==&quot;Racing&quot;, 1, 0) ) %&gt;% mutate(Sports = ifelse(Genre==&quot;Sports&quot;, 1, 0) ) %&gt;% mutate(MOBA = ifelse(Genre==&quot;Multiplayer Online Battle Arena&quot;, 1, 0) ) %&gt;% mutate(MOBA = ifelse(Genre==&quot;Multiplayer Online Battle Arena&quot;, 1, 0) ) %&gt;% mutate(Strategy = ifelse(Genre==&quot;Strategy&quot;, 1, 0) ) %&gt;% mutate(TPS = ifelse(Genre==&quot;Third-Person Shooter&quot;, 1, 0) ) %&gt;% select(CollectibleCardGame:Racing, Sports:TPS, OnlineEarnings:ReleaseDate) </code></pre>
<p>LASSO shows that all of the Genres and selected predictors (except <code>TotalTournaments</code>) have nonzero coeffient estimates. It is interesting that the lambda.min reduces the coefficients by 1 while lambda.1se retains all of the coefficients.</p>
</div>
<div id="fold-cv-for-lasso" class="section level2">
<h2>10-fold CV for LASSO!</h2>
<pre class="r"><code>set.seed(1234)
k = 10


data &lt;- esportb[sample(nrow(esportb)),] 
folds &lt;- cut(seq(1:nrow(data)),breaks=k,labels=F) 

diags &lt;- NULL
for(i in 1:k){        
train &lt;- data[folds!=i,]
test &lt;- data[folds==i,]  

truth &lt;- test$y

fit &lt;- glm(y ~ Genre + OnlineEarnings + TotalPlayers + ReleaseDate, data=train, family=&quot;binomial&quot;)
probs &lt;- predict(fit, newdata = test, type=&quot;resp&quot;)

diags &lt;- rbind(diags,class_diag(probs,test$y))
}

summarize_all(diags,mean) </code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.9183635 0.9222326 0.9147702 0.9449871 0.9801063</code></pre>
<p>The average classification diagnostics are:
The Accuracy is 0.9183635.
The Sensitivity (TPR) is 0.9222326.
The Specificity (TNR) is 0.9147702.
The Precision (PPV) is 0.9449871.
The AUC is 0.9801063 which is less than the logistic regressions above, but still proves to be a great model.</p>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Overall, it was really interesting to model the data from the esports tournament data set. I created a great model for predicting if a given game will be highly prized based on these predictors: <code>Genre</code> + <code>TotalTournaments</code> + <code>OnlineEarnings</code> + <code>TotalPlayers</code> + <code>ReleaseDate</code>.</p>
</div>
